### ISSUE TITLE
invalid line number' not building , i like to see this demon on duty,,'' i really need help from the farmily

### ISSUE THREAD

**Issue by virginhybrid78** [optiv/ScareCrow#26]
go build ScareCrow.go
# ScareCrow/Loader
 /home/virginhybrid78/Downloads/ScareCrow-main/Struct/Struct.go:213: error: invalid export data for ‘Macro’: invalid line number
 /home/virginhybrid78/Downloads/ScareCrow-main/Struct/Struct.go:212: error: invalid export data for ‘Macro’: invalid line number

**Comment by Tylous** [comment]
That's a weird error could you provide me the full terminal output, the line content of the version you have of  Struct.go 213 and 212.

**Comment by Tylous** [comment]
Closing due to lack of response.
