### ISSUE TITLE
redeclared in this block

### ISSUE THREAD

**Issue by timwhitez** [optiv/ScareCrow#32]
ScareCrow_3.0_windows_amd64.exe -I c.bin -Loader binary  -domain www.microsoft.com

![image](https://user-images.githubusercontent.com/36320909/137247916-e255953c-2d85-4973-a40d-4df9ccf57e97.png)

**Comment by timwhitez** [comment]
Linux version work well

**Comment by Tylous** [comment]
Thank you for the heads up I think its an issue with golang and windows compiling this type of loader with all my custom edits. I will dig into this.

**Comment by Tylous** [comment]
Looks to be another windows issue. I am gonna close this as right now there is no fix planned, besides using windows as the OS to build the loaders on.
