### ISSUE TITLE
cmd.Run() failed with exit status 0xffffffff

### ISSUE THREAD

**Issue by a1phaboy** [optiv/ScareCrow#39]
when I after step : [*] Signing Outlook.exe With a Fake Cert, then I got cmd.Run() failed with exit status 0xffffffff.
my env:
go version go1.17.1 windows/amd64

OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)

osslsigncode 2.2, using:
        OpenSSL 1.1.1k  25 Mar 2021 (Library: OpenSSL 1.1.1k  25 Mar 2021)
        libcurl/7.78.0 OpenSSL/1.1.1k zlib/1.2.11

**Comment by a1phaboy** [comment]
Although I rebuild the project, the error still appear

**Comment by Tylous** [comment]
Can you please confirm the following are installed and that you are not on a windows machine?
- openssl
- osslsigncode
- mingw-w64

**Comment by a1phaboy** [comment]
yep, I'm on a windows machine and my version is 10.0.19042, my mingw-w64 version is x86_64-8.1.0-release-posix-seh-rt_v6-rev0 and lt's in my %path%, but the error:"exec: "": executable file not found in %PATH%: "seems that throw out on the 94 line in ScareCrow.go, am I lost anything?

**Comment by Tylous** [comment]
There are known issues with calling osslsigncode on Windows, I would recommend building it on Linux or OSX.

**Comment by serkonda7** [comment]
May this be reopened to be easier recognizeable by others?
It could be tagged with something like `dependency-issue`
