### ISSUE TITLE
cmd.run() failed with exit status 1

### ISSUE THREAD

**Issue by tgelliott196** [optiv/ScareCrow#41]
[failedtomakeexe.docx](https://github.com/optiv/ScareCrow/files/8005151/failedtomakeexe.docx)

when run makes random files onenote onedrive excel word, but never creates out file.

**Comment by Tylous** [comment]
Can you please provide the exact command you are running.

**Comment by tgelliott196** [comment]
I've tried multiple variants of: 

ScareCrow_3.01_windows_amd64.exe -I test.bin -domain www.microsoft.com
or
ScareCrow_3.01_windows_amd64.exe -I test.bin -domain www.microsoft.com -Loader dll -O blah.dll
or 
ScareCrow_3.01_windows_amd64.exe -I test.bin -domain www.microsoft.com -Loader excel

**Comment by Tylous** [comment]
This is a windows issue playing not well with OSSSIGNCODE, I would recommend you try on Linux or OSX

**Comment by tgelliott196** [comment]
Thank you.  I'll put it on linux
