### ISSUE TITLE
Feature Request: Output parameter

### ISSUE THREAD

**Issue by GeorgePatsias** [optiv/ScareCrow#46]
Hey man great work!

I would like to ask for a feature request when you find time and you want it as well :)

Feature: To add an output parameter that specifies the location of the final Payload/Loader on where it is going to be saved.

For example:
./ScareCrow ......  --output /home/user/Desktop/
(The user wants the final payload to be saved at the Desktop)

Thanks in advance,
Keep up the great work!

**Comment by Tylous** [comment]
I will look into this for the next update.

**Comment by GeorgePatsias** [comment]
Thanks man, appreciate it!

**Comment by Tylous** [comment]
Just pushed a new update with this feature in it.
