### ISSUE TITLE
Previous declaration when using any other loader

### ISSUE THREAD

**Issue by g33gs** [optiv/ScareCrow#50]
Unable to find a resolution for this one. Any time I attempt to run using anything other than the default, it am presented an error from go I believe, relating to a previous declaration::

`[*] Compiling Payload
exit status 1: go list error: exit status 2: # igYzBjFwiyh
./tcpmon.go:10:3: base64 redeclared as imported package name
        /home/user/tools/ScareCrow/tcpmon/tcpmon.go:8:3: previous declaration`

I didn't see this anywhere else, could it be a golang issue with the new version or something related to my current setup?

Thanks! And thank you for your work, it's fantastic.

**Comment by Tylous** [comment]
This should be addressed in the most recent update (that’s a few hours old) can you confirm are on the latest from today? And what commands you are running so I can replicate it on my end. Thank you

**Comment by g33gs** [comment]
UPDATE: 
This appears to be a potential issue using Kali WSL. Running `./Scarecrow -I beacon.bin -domain www.cisco.com -Loader wscript -O test.js` resulted in successful creation.

**Comment by g33gs** [comment]
Awesome timing on my part, looks like I was a version behind. Pulling latest is now working as expected! 

Thanks again!
