### ISSUE TITLE
Injection compiling 

### ISSUE THREAD

**Issue by shrek3n** [optiv/ScareCrow#52]
Tried as well with disabling amsi,etw and sleep.

**Comment by Azrotronik** [comment]
It seems the bug happens upon using the -injection flag, I can replicate this using 
scarecrow -I sgn.raw -Loader dll -domain libreoffice.org -injection svchost.exe

Will investigate in a few.

**Comment by GeorgePatsias** [comment]
> It seems the bug happens upon using the -injection flag, I can replicate this using scarecrow -I sgn.raw -Loader dll -domain libreoffice.org -injection svchost.exe
> 
> Will investigate in a few.

You need to add the full path of the injection.
e.g. C:\Windows\System32\svchost.exe

**Comment by Azrotronik** [comment]
`You need to add the full path of the injection.
e.g. C:\Windows\System32\svchost.exe`

Yes, i have initially added the path, i shortened it here, but the issue still persists, i think the issue may have to do with garble.

**Comment by Tylous** [comment]
This has nothing with the path it has to do with a recent update to the dependencies. I will update the repo shortly.

**Comment by Tylous** [comment]
Repo and releases have been updated to address this.
