### ISSUE TITLE
Windows 10 bug

### ISSUE THREAD

**Issue by ghost** [optiv/ScareCrow#55]
exec: "": executable file not found in %PATH%:
[+] Payload Compiled
[*] Signing mimosys.dll With a Fake Cert
2022/04/15 12:46:03 cmd.Run() failed with exit status 0xffffffff

I have downloaded osslsigncode and put it on path env to sign and i i'll give this error

not work on windows 10

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/91875992/163592258-68d7bcc0-3d5a-49c9-a20a-606834456dba.png)

**Comment by Tylous** [comment]
Are you compiling it on Windows?

**Comment by Tylous** [comment]
closing due to lack of response
