### ISSUE TITLE
Windows defender new sandbox

### ISSUE THREAD

**Issue by ghost** [optiv/ScareCrow#56]
Windows defender have a new sandbox now, not executing any script on the system

**Comment by Tylous** [comment]
I am sorry this statement does make much sense, can you elaborate on it.

**Comment by NotSoEthical** [comment]
Any useful  tips for bypassing Windows Defender?

**Comment by Tylous** [comment]
Since Defender has no userland hooks I would use the -unmodified flag since unhook is pretty much useless
