### ISSUE TITLE
'.exp' files are not the compiled Go files

### ISSUE THREAD

**Issue by vysecurity** [optiv/ScareCrow#63]
I noticed the .exp files generated are not the same as the go files on disk.

E.g. it always compiles the original .go file and doesn't compile the changed / modified code?

**Comment by vysecurity** [comment]
What is the logic behind hardcoding a base64 encoded zip file into the loader?

**Comment by Tylous** [comment]
This is closed, are all your questions answered? If note,  the base64  encoded zip is not in the loader its in the framework of Scarecrow to help generate loaders without the need for all the subfolders and whatnot. As for your first question I am not tracking can you elaborate.

**Comment by vysecurity** [comment]
Hey Tylous. It's alright, figured it out.
